### ISSUE TITLE
Installation requires restart

### ISSUE THREAD

**Issue by HoldYourWaffle** [chylex/IntelliJ-Keep-Editor-Popups-While-Debugging#1] opened 2022-08-01 10:44 UTC
The description says this amazing plugin should start working even in the middle of a debugging session, but this wasn't the case for me. Although inconvenient, a quick restart fixed this :)

Version info:
```
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    net.bounceme.monkee.monarcula (1.1.1)
    com.chylex.intellij.keeppopupswhiledebugging (1.1)
    Batch Scripts Support (1.0.13)

Kotlin: 222-1.7.10-release-334-IJ3345.118
```

**Comment by chylex** [comment] 2022-08-01 10:59
Did you wait for IntelliJ to rescan files and refresh the editor after the plugin was installed? It happens automatically but it takes a few seconds.

**Comment by chylex** [comment] 2023-01-10 06:28
Closing as can't reproduce.

**Closed as not planned by chylex** 2023-01-10 06:28 UTC
